"""
SQLAlchemy 2.0 declarative base and shared mixins.
"""
import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """
    Project-wide declarative base.
    All models inherit from this — Alembic autogenerate uses it as the metadata source.
    """
    type_annotation_map: dict[type, Any] = {}


class UUIDPrimaryKeyMixin:
    """Adds a UUID primary key generated by PostgreSQL's gen_random_uuid()."""
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """Adds created_at / updated_at columns with automatic server-side defaults."""
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class SoftDeleteMixin:
    """Logical deletion without physical row removal."""
    is_active: Mapped[bool] = mapped_column(default=True, nullable=False)
